service: fastify-link-shortener

plugins:
  - serverless-offline
  - serverless-pseudo-parameters

package:
  exclude:
    - README.md

custom:
  stage: ${self:provider.stage}
  linkTableName: link-table-${self:custom.stage}

provider:
  name: aws
  runtime: nodejs12.x
  stackName: ${self:service}-${self:custom.stage}
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}

functions:
  shortener:
    handler: src/handler/app.handler
    name: ${self:service}-${self:custom.stage}
    description: fastify link shortener
    timeout: 30
    memorySize: 128
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
        Resource:
          { "Fn::GetAtt": [LinkTableDB, Arn] }
    environment:
      link_table_name: ${self:custom.linkTableName}
    events:
      - http:
          path: /{id}
          method: GET
      - http:
          path: /
          method: POST

resources:
  Description: >
    Fastify link shortener service
  Resources:
    LinkTableDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.linkTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        Tags:
          - Key: 'Name'
            Value: ${self:custom.linkTableName}
          - Key: 'Environment'
            Value: ${self:custom.stage}
