service: fastify-link-shortener

plugins:
  - serverless-offline
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function

package:
  exclude:
    - README.md

custom:
  stage: ${self:provider.stage}
  linkTableName: link-table-${self:custom.stage}

provider:
  name: aws
  runtime: nodejs12.x
  stackName: ${self:service}-${self:custom.stage}
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
#  apiGateway:
#    restApiId:
#      Ref: FastifyLinkApi
#    restApiRootResourceId:
#      Fn::GetAtt:
#        - FastifyLinkApi
#        - RootResourceId

functions:
  shortener:
    handler: src/handler/app.handler
    name: ${self:service}-${self:custom.stage}
    description: fastify link shortener
    timeout: 30
    memorySize: 128
    iamRoleStatementsName: ${self:service}-${self:custom.stage}-role
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
        Resource:
          { "Fn::GetAtt": [LinkTableDB, Arn] }
    environment:
      link_table_name: ${self:custom.linkTableName}
    events:
      - http:
          path: /{id}
          method: GET
      - http:
          path: /
          method: POST

resources:
  Description: >
    Fastify link shortener service
  Resources:
    LinkTableDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.linkTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        Tags:
          - Key: 'Name'
            Value: ${self:custom.linkTableName}
          - Key: 'Environment'
            Value: ${self:custom.stage}

#    FastifyLinkApi:
#      Type: AWS::ApiGateway::RestApi
#      Properties:
#        Name: FastifyLinkApi
#    FastifyLinkApiMaping:
#      Type: AWS::ApiGateway::BasePathMapping
#      Properties:
#        BasePath: l
#        DomainName: your-url.com
#        RestApiId:
#          Ref: FastifyLinkApi
#        Stage: dev
